version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: focuslight-backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - SESSION_SECRET=${SESSION_SECRET:-focus-lamp-secret}
    depends_on:
      - db
    networks:
      - focuslight-network
    volumes:
      - ./uploads:/app/uploads

  db:
    image: postgres:15-alpine
    container_name: focuslight-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER:-focuslight}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
      - POSTGRES_DB=${DB_NAME:-focuslight}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/dumps:/dumps
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - focuslight-network

networks:
  focuslight-network:
    driver: bridge

volumes:
  postgres-data:
