name: Deploy Backend

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup QEMU for arm64 builds
        uses: docker/setup-qemu-action@v3

      - name: Setup environment variables
        run: echo "TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Backend Docker image (multi-arch)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./server/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/focuslight-backend:${{ env.TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/focuslight-backend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/focuslight-backend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/focuslight-backend:buildcache,mode=max

      - name: Deployment notification
        run: |
          echo "✅ Backend image pushed: ${{ env.TAG }}"
          echo "💡 docker pull ${{ secrets.DOCKERHUB_USERNAME }}/focuslight-backend:latest"
